here we read fasta column of the .csv file and selece 1-letter sequences in each row. then save it in a file. then use seq2nu.py code to calculate SHD, SCD ... of that sequence. I repeat this for all the fasta rows (sequences) and save the result which is feature values of each sequence in a .csv file.
for example for .csv of 64 exp samples we have 64 sequences (rows) and our code do the calulation 64 times and save all in anothet csv file. thankGOD! 

In [19]:
import pandas as pd

# Load the excel file
input_file_path = '41592_2023_2159_MOESM4_ESM.xlsx'  # Replace with your actual file path
data = pd.read_excel(input_file_path)

# Specify the column name you want to display
column_name = ' sequence'  # Replace with your actual column name

# Name or index of the sheet you want to read
sheet_name = 'Table_S8'  # Replace with the actual sheet name or use an index (e.g., 0 for the first sheet)

# Read the specific sheet
data = pd.read_excel(input_file_path, sheet_name=sheet_name)
# Print the column names
#print(data.columns)


# Display the column
if column_name in data.columns:
    print(data[column_name])
else:
    print(f"Column '{column_name}' not found in the excel file.")

# to calculate N ( sequence length)#########################################
for sequence in data[column_name]:
    sequence_length = len(sequence)
    print(sequence_length)


0       GSMASASSSQGGSSGSGNFGGGGGGGFGGNDNFGGGGNFSGSGGF...
1       GSMASASSSQKGKSGSGNFGGGKGGGFGGNDNFGKGGNFSGKGGF...
2       GSMASASSSQRGRSGSGNYGGGRGGGYGGNDNYGRGGNYSGRGGY...
3       GSMASASSSQGGSSGSGNYGGGGGGGYGGNDNYGGGGNYSGSGGY...
4       GSMASASSSQRGKSGSGNFGGGRGGGFGGNDNFGRGGNFSGRGGF...
                             ...                        
132     MGHHHHHHENLYFQGELLGEYVGQEGKPQKLRVSCEAPGDGDPFQ...
133     GPDASSPGGKKILNGGTPDIPSTGLLPGQAQETPGYPYSDSSSIL...
134     GPHMQVPRTHRLITLADHICQIITQDFARNQVPSQASTSTFQTSP...
135     MADERKDEGKAPHWTSASLTEAAAHPHSPEMKDQGGSGEGLSRSA...
136     GPPGSMAGGGGSSDGSGRAAGRRASRSSGRARRGRHEPGLGGPAE...
Name:  sequence, Length: 137, dtype: object
138
138
138
138
138
138
138
138
138
138
138
138
138
138
138
138
138
138
138
138
138
138
138
138
138
138
141
84
101
325
151
186
119
188
104
143
99
99
47
25
102
62
131
149
100
142
293
148
71
305
154
119
179
126
115
83
80
39
108
108
108
108
108
108
92
103
335
335
157
112
82
125
76
313
82
93
82
335
335
335
335
335
335
353
353
353
4

In [1]:
#step1: read the data set to choose sequeces out of it
import pandas as pd
import csv
import subprocess

# Load the excel file
input_file_path = '41592_2023_2159_MOESM4_ESM.xlsx'  # Replace with your actual file path
output_file_path = 'features.xlsx'  # Path to save the final features

# Specify the column name you want to display
column_name = ' sequence'  # Replace with your actual column name

# Name or index of the sheet you want to read
sheet_name = 'Table_S8'  # Replace with the actual sheet name or use an index (e.g., 0 for the first sheet)

# Read the specific sheet
data = pd.read_excel(input_file_path, sheet_name=sheet_name)


In [56]:
#step2: run the Keresten code on the sequences from dataset to get their features 
import numpy as np

# Remove the identifier (e.g., 'Q99457_1_97') and flatten the list if necessary
def extract_values(line):
    return [float(x) for x in line if isinstance(x, str) and x.replace('.', '', 1).replace('-', '', 1).isdigit()]

feature_values=np.zeros((137,11))

# Loop through each sequence in the column ( read sequences and run the code and calculate the features. thankGOD!

for index, sequence in data[column_name].items():
   
    # Ensure the sequence is a string
    sequence = str(sequence)
    #print(f"Processing sequence at index {index}: {sequence}")

    # Run the external Python script with the sequence
    result = subprocess.run(['python', 'IDRlab_modified3.py', sequence],capture_output=True, text=True)  # Adjust 'IDRlab_modified.py' to your script name


    output_lines = [line for line in result.stdout.splitlines() if line.strip()]
    


    feature_values_4 = output_lines[3].split()  # Extracts the values in the second row. thankGOD!
    feature_values_6= output_lines[5].split()
    
    feature_values_4 = extract_values(feature_values_4)
    feature_values_6 = extract_values(feature_values_6)
    
    feature_values[index]=  feature_values_4 + feature_values_6
print(feature_values)


[[ 0.015  0.     0.    ...  0.31   0.051 -0.007]
 [ 0.088  0.     0.    ...  0.194  0.124  0.066]
 [ 0.015  0.073  0.    ...  0.194  0.124  0.066]
 ...
 [ 0.041  0.066  0.052 ...  0.159  0.214  0.007]
 [ 0.077  0.058  0.077 ...  0.149  0.251  0.024]
 [ 0.     0.184  0.041 ...  0.286  0.265  0.143]]


In [59]:
# Step 3: Combine both header and resulted feature lines into a DataFrame
headers = ['fK', 'fR', 'fE', 'fD', 'fARO', 'mean_lambda', 'SHD', 'SCD', 'kappa', 'FCR', 'NCPR']  # Adjust header names as needed
print(len(headers))
# Initialize an empty DataFrame for storing features
output_features=pd.DataFrame()

for row in feature_values:
    df_row = pd.DataFrame([row], columns=headers) # Convert each row into a DataFrame
    output_features = pd.concat ([output_features, df_row], ignore_index=True)  # Append to main DataFrame

print (output_features)

11
        fK     fR     fE     fD   fARO  mean_lambda    SHD    SCD  kappa  \
0    0.015  0.000  0.000  0.029  0.146        0.605  5.453 -0.209  0.310   
1    0.088  0.000  0.000  0.029  0.139        0.571  5.160  1.796  0.194   
2    0.015  0.073  0.000  0.029  0.139        0.621  5.593  1.796  0.194   
3    0.015  0.000  0.000  0.029  0.146        0.615  5.541 -0.209  0.310   
4    0.036  0.051  0.000  0.029  0.139        0.599  5.408  1.796  0.194   
..     ...    ...    ...    ...    ...          ...    ...    ...    ...   
132  0.044  0.035  0.096  0.123  0.053        0.387  3.318  3.018  0.369   
133  0.020  0.000  0.041  0.102  0.041        0.436  3.617  2.030  0.214   
134  0.041  0.066  0.052  0.052  0.041        0.425  4.406 -1.169  0.159   
135  0.077  0.058  0.077  0.036  0.026        0.402  4.603 -5.887  0.149   
136  0.000  0.184  0.041  0.020  0.000        0.534  3.717  1.134  0.286   

       FCR   NCPR  
0    0.051 -0.007  
1    0.124  0.066  
2    0.124  0.066  
3   

In [61]:
# Step 4: Write the df to Excel
output_file_path = "features.xlsx"
output_features.to_excel(output_file_path, index=False)

print(f"Data has been written to {output_file_path}")

Data has been written to features.xlsx
